modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="${mod_issues}"
license="${license_name}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description="${mod_description}"

[[dependencies.catlib]]
modId="catlib"
mandatory=true
versionRange="[${catlib_version},)"
ordering="NONE"
side="BOTH"
